namespace illShop.Client.Pages.UIHandler
{
    public partial class ContextDesign
    {
        List<string> iconsList = new List<string>()
        {
            "fas fa-basketball-ball",
            "fas fa-bicycle",
            "fas fa-beer",
            "fas fa-blender-phone",
            "fab fa-btc",
            "fas fa-business-time",
            "fas fa-cart-arrow-down",
            "fas fa-carrot",
            "fas fa-cocktail",
            "fab fa-android",
            "fas fa-capsules",
            "fas fa-car",
            "fas fa-bed",
            "fas fa-chalkboard",
            "fas fa-couch",
            "fas fa-tshirt",
            "fas fa-user-tie",
            "fas fa-mitten",
            "fas fa-shoe-prints",
            "fas fa-hat-cowboy",
             "fas fa-basketball-ball",
            "fas fa-bicycle",
            "fas fa-beer",
            "fas fa-blender-phone",
            "fab fa-btc",
            "fas fa-business-time",
            "fas fa-cart-arrow-down",
            "fas fa-carrot",
            "fas fa-cocktail",
            "fab fa-android",
            "fas fa-capsules",
            "fas fa-car",
            "fas fa-bed",
            "fas fa-chalkboard",
            "fas fa-couch",
            "fas fa-tshirt",
            "fas fa-user-tie",
            "fas fa-mitten",
            "fas fa-shoe-prints", "fas fa-basketball-ball",
            "fas fa-bicycle",
            "fas fa-beer",
            "fas fa-blender-phone",
            "fab fa-btc",
            "fas fa-business-time",
            "fas fa-cart-arrow-down",
            "fas fa-carrot",
            "fas fa-cocktail",
            "fab fa-android",
            "fas fa-capsules",
            "fas fa-car",
            "fas fa-bed",
            "fas fa-chalkboard",
            "fas fa-couch",
            "fas fa-tshirt",
            "fas fa-user-tie",
            "fas fa-mitten",
            "fas fa-shoe-prints", "fas fa-basketball-ball",
            "fas fa-bicycle",
            "fas fa-beer",
            "fas fa-blender-phone",
            "fab fa-btc",
            "fas fa-business-time",
            "fas fa-cart-arrow-down",
            "fas fa-carrot",
            "fas fa-cocktail",
            "fab fa-android",
            "fas fa-capsules",
            "fas fa-car",
            "fas fa-bed",
            "fas fa-chalkboard",
            "fas fa-couch",
            "fas fa-tshirt",
            "fas fa-user-tie",
            "fas fa-mitten",
            "fas fa-shoe-prints",
        };
    }
}
